/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "qroma-lights-commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SetQromaStrip_WS2812FX_Segments, SetQromaStrip_WS2812FX_Segments, AUTO)


PB_BIND(SetQromaStrip_WS2812FX_SegmentAnimation, SetQromaStrip_WS2812FX_SegmentAnimation, AUTO)


PB_BIND(SetQromaStrip_WS2812FX_Brightness, SetQromaStrip_WS2812FX_Brightness, AUTO)


PB_BIND(SetQromaStrip_WS2812FX_IoSettings, SetQromaStrip_WS2812FX_IoSettings, AUTO)


PB_BIND(SaveQromaStrip_CurrentState, SaveQromaStrip_CurrentState, AUTO)


PB_BIND(QromaStripCommand, QromaStripCommand, AUTO)


PB_BIND(QromaStripResponse, QromaStripResponse, AUTO)


PB_BIND(QromaStrip_Status, QromaStrip_Status, AUTO)


PB_BIND(QpmCommand_SetQromaStripName, QpmCommand_SetQromaStripName, AUTO)


PB_BIND(SetQromaDeviceName, SetQromaDeviceName, AUTO)


PB_BIND(UseCurrentSetupOnStartup, UseCurrentSetupOnStartup, AUTO)


PB_BIND(QromaLightsCommand, QromaLightsCommand, AUTO)


PB_BIND(QromaLightsResponse, QromaLightsResponse, 2)



