/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MY_PROJECT_MESSAGES_PB_H_INCLUDED
#define PB_MY_PROJECT_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MathOperation {
    MathOperation_MathOp_NotSet = 0,
    MathOperation_MathOp_Add = 1,
    MathOperation_MathOp_Subtract = 2,
    MathOperation_MathOp_Add_And_Subtract = 3
} MathOperation;

typedef enum _UpdateType {
    UpdateType_UpdateType_NotSet = 0,
    UpdateType_UpdateType_None = 1,
    UpdateType_UpdateType_Interval = 2,
    UpdateType_UpdateType_ProgressIndicator = 3
} UpdateType;

typedef enum _NoArgCommands {
    NoArgCommands_Nac_NotSet = 0,
    NoArgCommands_Nac_GetBoardDetailsRequest = 1,
    NoArgCommands_Nac_LoadBoardConfiguration = 2,
    NoArgCommands_Nac_RestartDevice = 3
} NoArgCommands;

/* Struct definitions */
typedef struct _HelloQromaRequest {
    char name[20];
} HelloQromaRequest;

typedef struct _HelloQromaResponse {
    char response[50];
    uint32_t callCount;
    uint32_t nameLength;
} HelloQromaResponse;

typedef struct _MathRequest {
    uint32_t a;
    uint32_t b;
    MathOperation op;
} MathRequest;

typedef struct _MathResult_Add {
    uint32_t result;
} MathResult_Add;

typedef struct _MathResult_Subtract {
    uint32_t result;
} MathResult_Subtract;

typedef struct _MathResult_AddAndSubtract {
    uint32_t addResult;
    uint32_t subtractResult;
} MathResult_AddAndSubtract;

typedef struct _MathResponse {
    pb_size_t which_response;
    union {
        MathResult_Add addResult;
        MathResult_Subtract subtractResult;
        MathResult_AddAndSubtract addAndSubtractResult;
    } response;
} MathResponse;

typedef struct _FwUpdateConfiguration {
    UpdateType updateType;
    uint32_t updateIntervalInMs;
} FwUpdateConfiguration;

typedef struct _SetUpdateConfiguration {
    bool has_updateConfiguration;
    FwUpdateConfiguration updateConfiguration;
    bool saveConfiguration;
} SetUpdateConfiguration;

typedef struct _SetUpdateConfigurationResponse {
    bool success;
    bool has_updateConfiguration;
    FwUpdateConfiguration updateConfiguration;
} SetUpdateConfigurationResponse;

typedef struct _UptimeUpdateResponse {
    uint32_t uptime;
} UptimeUpdateResponse;

typedef struct _ProgressIndicatorUpdateResponse {
    char progressIndicator[50];
} ProgressIndicatorUpdateResponse;

typedef struct _UpdateResponse {
    pb_size_t which_update;
    union {
        UptimeUpdateResponse uptimeUpdateResponse;
        ProgressIndicatorUpdateResponse progressIndicatorUpdateResponse;
    } update;
} UpdateResponse;

typedef struct _PingRequest {
    uint32_t pingId;
} PingRequest;

typedef struct _PingResponse {
    uint32_t pingId;
    uint32_t uptime;
} PingResponse;

typedef struct _MyProjectDetails {
    char projectName[50];
} MyProjectDetails;

typedef struct _FirmwareDetails {
    char version[30];
    char buildTime[30];
    char boardName[30];
} FirmwareDetails;

typedef struct _GetBoardDetailsRequest {
    bool ignoreThis;
} GetBoardDetailsRequest;

typedef struct _GetBoardDetailsResponse {
    bool has_projectDetails;
    MyProjectDetails projectDetails;
    bool has_firmwareDetails;
    FirmwareDetails firmwareDetails;
} GetBoardDetailsResponse;

typedef struct _SetBoardLightColorRequest {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
} SetBoardLightColorRequest;

typedef struct _SetBoardLightColorResponse {
    bool success;
    char message[50];
} SetBoardLightColorResponse;

typedef struct _LoadBoardConfigurationResponse {
    bool success;
    bool has_loadedConfiguration;
    FwUpdateConfiguration loadedConfiguration;
} LoadBoardConfigurationResponse;

typedef struct _InvalidCommandResponse {
    char message[50];
} InvalidCommandResponse;

typedef struct _MyProjectCommand {
    pb_size_t which_command;
    union {
        NoArgCommands noArgCommand;
        HelloQromaRequest helloQromaRequest;
        MathRequest mathRequest;
        SetUpdateConfiguration setUpdateConfiguration;
        PingRequest pingRequest;
        GetBoardDetailsRequest getBoardDetailsRequest;
        SetBoardLightColorRequest setBoardLightColorRequest;
    } command;
} MyProjectCommand;

typedef struct _MyProjectResponse {
    pb_size_t which_response;
    union {
        InvalidCommandResponse invalidCommandResponse;
        HelloQromaResponse helloQromaResponse;
        MathResponse mathResponse;
        SetUpdateConfigurationResponse setUpdateConfigurationResponse;
        PingResponse pingResponse;
        UpdateResponse updateResponse;
        SetBoardLightColorResponse setBoardLightColorResponse;
        GetBoardDetailsResponse getBoardDetailsResponse;
        LoadBoardConfigurationResponse loadBoardConfigurationResponse;
    } response;
} MyProjectResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MathOperation_MIN MathOperation_MathOp_NotSet
#define _MathOperation_MAX MathOperation_MathOp_Add_And_Subtract
#define _MathOperation_ARRAYSIZE ((MathOperation)(MathOperation_MathOp_Add_And_Subtract+1))

#define _UpdateType_MIN UpdateType_UpdateType_NotSet
#define _UpdateType_MAX UpdateType_UpdateType_ProgressIndicator
#define _UpdateType_ARRAYSIZE ((UpdateType)(UpdateType_UpdateType_ProgressIndicator+1))

#define _NoArgCommands_MIN NoArgCommands_Nac_NotSet
#define _NoArgCommands_MAX NoArgCommands_Nac_RestartDevice
#define _NoArgCommands_ARRAYSIZE ((NoArgCommands)(NoArgCommands_Nac_RestartDevice+1))



#define MathRequest_op_ENUMTYPE MathOperation





#define FwUpdateConfiguration_updateType_ENUMTYPE UpdateType
















#define MyProjectCommand_command_noArgCommand_ENUMTYPE NoArgCommands



/* Initializer values for message structs */
#define HelloQromaRequest_init_default           {""}
#define HelloQromaResponse_init_default          {"", 0, 0}
#define MathRequest_init_default                 {0, 0, _MathOperation_MIN}
#define MathResult_Add_init_default              {0}
#define MathResult_Subtract_init_default         {0}
#define MathResult_AddAndSubtract_init_default   {0, 0}
#define MathResponse_init_default                {0, {MathResult_Add_init_default}}
#define FwUpdateConfiguration_init_default       {_UpdateType_MIN, 0}
#define SetUpdateConfiguration_init_default      {false, FwUpdateConfiguration_init_default, 0}
#define SetUpdateConfigurationResponse_init_default {0, false, FwUpdateConfiguration_init_default}
#define UptimeUpdateResponse_init_default        {0}
#define ProgressIndicatorUpdateResponse_init_default {""}
#define UpdateResponse_init_default              {0, {UptimeUpdateResponse_init_default}}
#define PingRequest_init_default                 {0}
#define PingResponse_init_default                {0, 0}
#define MyProjectDetails_init_default            {""}
#define FirmwareDetails_init_default             {"", "", ""}
#define GetBoardDetailsRequest_init_default      {0}
#define GetBoardDetailsResponse_init_default     {false, MyProjectDetails_init_default, false, FirmwareDetails_init_default}
#define SetBoardLightColorRequest_init_default   {0, 0, 0}
#define SetBoardLightColorResponse_init_default  {0, ""}
#define LoadBoardConfigurationResponse_init_default {0, false, FwUpdateConfiguration_init_default}
#define InvalidCommandResponse_init_default      {""}
#define MyProjectCommand_init_default            {0, {_NoArgCommands_MIN}}
#define MyProjectResponse_init_default           {0, {InvalidCommandResponse_init_default}}
#define HelloQromaRequest_init_zero              {""}
#define HelloQromaResponse_init_zero             {"", 0, 0}
#define MathRequest_init_zero                    {0, 0, _MathOperation_MIN}
#define MathResult_Add_init_zero                 {0}
#define MathResult_Subtract_init_zero            {0}
#define MathResult_AddAndSubtract_init_zero      {0, 0}
#define MathResponse_init_zero                   {0, {MathResult_Add_init_zero}}
#define FwUpdateConfiguration_init_zero          {_UpdateType_MIN, 0}
#define SetUpdateConfiguration_init_zero         {false, FwUpdateConfiguration_init_zero, 0}
#define SetUpdateConfigurationResponse_init_zero {0, false, FwUpdateConfiguration_init_zero}
#define UptimeUpdateResponse_init_zero           {0}
#define ProgressIndicatorUpdateResponse_init_zero {""}
#define UpdateResponse_init_zero                 {0, {UptimeUpdateResponse_init_zero}}
#define PingRequest_init_zero                    {0}
#define PingResponse_init_zero                   {0, 0}
#define MyProjectDetails_init_zero               {""}
#define FirmwareDetails_init_zero                {"", "", ""}
#define GetBoardDetailsRequest_init_zero         {0}
#define GetBoardDetailsResponse_init_zero        {false, MyProjectDetails_init_zero, false, FirmwareDetails_init_zero}
#define SetBoardLightColorRequest_init_zero      {0, 0, 0}
#define SetBoardLightColorResponse_init_zero     {0, ""}
#define LoadBoardConfigurationResponse_init_zero {0, false, FwUpdateConfiguration_init_zero}
#define InvalidCommandResponse_init_zero         {""}
#define MyProjectCommand_init_zero               {0, {_NoArgCommands_MIN}}
#define MyProjectResponse_init_zero              {0, {InvalidCommandResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define HelloQromaRequest_name_tag               1
#define HelloQromaResponse_response_tag          1
#define HelloQromaResponse_callCount_tag         2
#define HelloQromaResponse_nameLength_tag        3
#define MathRequest_a_tag                        1
#define MathRequest_b_tag                        2
#define MathRequest_op_tag                       3
#define MathResult_Add_result_tag                1
#define MathResult_Subtract_result_tag           1
#define MathResult_AddAndSubtract_addResult_tag  1
#define MathResult_AddAndSubtract_subtractResult_tag 2
#define MathResponse_addResult_tag               1
#define MathResponse_subtractResult_tag          2
#define MathResponse_addAndSubtractResult_tag    3
#define FwUpdateConfiguration_updateType_tag     1
#define FwUpdateConfiguration_updateIntervalInMs_tag 2
#define SetUpdateConfiguration_updateConfiguration_tag 1
#define SetUpdateConfiguration_saveConfiguration_tag 2
#define SetUpdateConfigurationResponse_success_tag 1
#define SetUpdateConfigurationResponse_updateConfiguration_tag 2
#define UptimeUpdateResponse_uptime_tag          1
#define ProgressIndicatorUpdateResponse_progressIndicator_tag 1
#define UpdateResponse_uptimeUpdateResponse_tag  1
#define UpdateResponse_progressIndicatorUpdateResponse_tag 2
#define PingRequest_pingId_tag                   1
#define PingResponse_pingId_tag                  1
#define PingResponse_uptime_tag                  2
#define MyProjectDetails_projectName_tag         1
#define FirmwareDetails_version_tag              1
#define FirmwareDetails_buildTime_tag            2
#define FirmwareDetails_boardName_tag            3
#define GetBoardDetailsRequest_ignoreThis_tag    1
#define GetBoardDetailsResponse_projectDetails_tag 1
#define GetBoardDetailsResponse_firmwareDetails_tag 2
#define SetBoardLightColorRequest_red_tag        1
#define SetBoardLightColorRequest_green_tag      2
#define SetBoardLightColorRequest_blue_tag       3
#define SetBoardLightColorResponse_success_tag   1
#define SetBoardLightColorResponse_message_tag   2
#define LoadBoardConfigurationResponse_success_tag 1
#define LoadBoardConfigurationResponse_loadedConfiguration_tag 2
#define InvalidCommandResponse_message_tag       1
#define MyProjectCommand_noArgCommand_tag        1
#define MyProjectCommand_helloQromaRequest_tag   2
#define MyProjectCommand_mathRequest_tag         3
#define MyProjectCommand_setUpdateConfiguration_tag 4
#define MyProjectCommand_pingRequest_tag         5
#define MyProjectCommand_getBoardDetailsRequest_tag 6
#define MyProjectCommand_setBoardLightColorRequest_tag 7
#define MyProjectResponse_invalidCommandResponse_tag 1
#define MyProjectResponse_helloQromaResponse_tag 2
#define MyProjectResponse_mathResponse_tag       3
#define MyProjectResponse_setUpdateConfigurationResponse_tag 4
#define MyProjectResponse_pingResponse_tag       5
#define MyProjectResponse_updateResponse_tag     6
#define MyProjectResponse_setBoardLightColorResponse_tag 7
#define MyProjectResponse_getBoardDetailsResponse_tag 8
#define MyProjectResponse_loadBoardConfigurationResponse_tag 9

/* Struct field encoding specification for nanopb */
#define HelloQromaRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define HelloQromaRequest_CALLBACK NULL
#define HelloQromaRequest_DEFAULT NULL

#define HelloQromaResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   response,          1) \
X(a, STATIC,   SINGULAR, UINT32,   callCount,         2) \
X(a, STATIC,   SINGULAR, UINT32,   nameLength,        3)
#define HelloQromaResponse_CALLBACK NULL
#define HelloQromaResponse_DEFAULT NULL

#define MathRequest_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, UINT32,   a,                 1) \
X(a_, STATIC,   SINGULAR, UINT32,   b,                 2) \
X(a_, STATIC,   SINGULAR, UENUM,    op,                3)
#define MathRequest_CALLBACK NULL
#define MathRequest_DEFAULT NULL

#define MathResult_Add_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   result,            1)
#define MathResult_Add_CALLBACK NULL
#define MathResult_Add_DEFAULT NULL

#define MathResult_Subtract_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   result,            1)
#define MathResult_Subtract_CALLBACK NULL
#define MathResult_Subtract_DEFAULT NULL

#define MathResult_AddAndSubtract_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   addResult,         1) \
X(a, STATIC,   SINGULAR, UINT32,   subtractResult,    2)
#define MathResult_AddAndSubtract_CALLBACK NULL
#define MathResult_AddAndSubtract_DEFAULT NULL

#define MathResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,addResult,response.addResult),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,subtractResult,response.subtractResult),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,addAndSubtractResult,response.addAndSubtractResult),   3)
#define MathResponse_CALLBACK NULL
#define MathResponse_DEFAULT NULL
#define MathResponse_response_addResult_MSGTYPE MathResult_Add
#define MathResponse_response_subtractResult_MSGTYPE MathResult_Subtract
#define MathResponse_response_addAndSubtractResult_MSGTYPE MathResult_AddAndSubtract

#define FwUpdateConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    updateType,        1) \
X(a, STATIC,   SINGULAR, UINT32,   updateIntervalInMs,   2)
#define FwUpdateConfiguration_CALLBACK NULL
#define FwUpdateConfiguration_DEFAULT NULL

#define SetUpdateConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  updateConfiguration,   1) \
X(a, STATIC,   SINGULAR, BOOL,     saveConfiguration,   2)
#define SetUpdateConfiguration_CALLBACK NULL
#define SetUpdateConfiguration_DEFAULT NULL
#define SetUpdateConfiguration_updateConfiguration_MSGTYPE FwUpdateConfiguration

#define SetUpdateConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  updateConfiguration,   2)
#define SetUpdateConfigurationResponse_CALLBACK NULL
#define SetUpdateConfigurationResponse_DEFAULT NULL
#define SetUpdateConfigurationResponse_updateConfiguration_MSGTYPE FwUpdateConfiguration

#define UptimeUpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime,            1)
#define UptimeUpdateResponse_CALLBACK NULL
#define UptimeUpdateResponse_DEFAULT NULL

#define ProgressIndicatorUpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   progressIndicator,   1)
#define ProgressIndicatorUpdateResponse_CALLBACK NULL
#define ProgressIndicatorUpdateResponse_DEFAULT NULL

#define UpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update,uptimeUpdateResponse,update.uptimeUpdateResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update,progressIndicatorUpdateResponse,update.progressIndicatorUpdateResponse),   2)
#define UpdateResponse_CALLBACK NULL
#define UpdateResponse_DEFAULT NULL
#define UpdateResponse_update_uptimeUpdateResponse_MSGTYPE UptimeUpdateResponse
#define UpdateResponse_update_progressIndicatorUpdateResponse_MSGTYPE ProgressIndicatorUpdateResponse

#define PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pingId,            1)
#define PingRequest_CALLBACK NULL
#define PingRequest_DEFAULT NULL

#define PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pingId,            1) \
X(a, STATIC,   SINGULAR, UINT32,   uptime,            2)
#define PingResponse_CALLBACK NULL
#define PingResponse_DEFAULT NULL

#define MyProjectDetails_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   projectName,       1)
#define MyProjectDetails_CALLBACK NULL
#define MyProjectDetails_DEFAULT NULL

#define FirmwareDetails_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1) \
X(a, STATIC,   SINGULAR, STRING,   buildTime,         2) \
X(a, STATIC,   SINGULAR, STRING,   boardName,         3)
#define FirmwareDetails_CALLBACK NULL
#define FirmwareDetails_DEFAULT NULL

#define GetBoardDetailsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ignoreThis,        1)
#define GetBoardDetailsRequest_CALLBACK NULL
#define GetBoardDetailsRequest_DEFAULT NULL

#define GetBoardDetailsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  projectDetails,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  firmwareDetails,   2)
#define GetBoardDetailsResponse_CALLBACK NULL
#define GetBoardDetailsResponse_DEFAULT NULL
#define GetBoardDetailsResponse_projectDetails_MSGTYPE MyProjectDetails
#define GetBoardDetailsResponse_firmwareDetails_MSGTYPE FirmwareDetails

#define SetBoardLightColorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   red,               1) \
X(a, STATIC,   SINGULAR, UINT32,   green,             2) \
X(a, STATIC,   SINGULAR, UINT32,   blue,              3)
#define SetBoardLightColorRequest_CALLBACK NULL
#define SetBoardLightColorRequest_DEFAULT NULL

#define SetBoardLightColorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define SetBoardLightColorResponse_CALLBACK NULL
#define SetBoardLightColorResponse_DEFAULT NULL

#define LoadBoardConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  loadedConfiguration,   2)
#define LoadBoardConfigurationResponse_CALLBACK NULL
#define LoadBoardConfigurationResponse_DEFAULT NULL
#define LoadBoardConfigurationResponse_loadedConfiguration_MSGTYPE FwUpdateConfiguration

#define InvalidCommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define InvalidCommandResponse_CALLBACK NULL
#define InvalidCommandResponse_DEFAULT NULL

#define MyProjectCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (command,noArgCommand,command.noArgCommand),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,helloQromaRequest,command.helloQromaRequest),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,mathRequest,command.mathRequest),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setUpdateConfiguration,command.setUpdateConfiguration),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,pingRequest,command.pingRequest),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,getBoardDetailsRequest,command.getBoardDetailsRequest),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setBoardLightColorRequest,command.setBoardLightColorRequest),   7)
#define MyProjectCommand_CALLBACK NULL
#define MyProjectCommand_DEFAULT NULL
#define MyProjectCommand_command_helloQromaRequest_MSGTYPE HelloQromaRequest
#define MyProjectCommand_command_mathRequest_MSGTYPE MathRequest
#define MyProjectCommand_command_setUpdateConfiguration_MSGTYPE SetUpdateConfiguration
#define MyProjectCommand_command_pingRequest_MSGTYPE PingRequest
#define MyProjectCommand_command_getBoardDetailsRequest_MSGTYPE GetBoardDetailsRequest
#define MyProjectCommand_command_setBoardLightColorRequest_MSGTYPE SetBoardLightColorRequest

#define MyProjectResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,invalidCommandResponse,response.invalidCommandResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,helloQromaResponse,response.helloQromaResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,mathResponse,response.mathResponse),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,setUpdateConfigurationResponse,response.setUpdateConfigurationResponse),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,pingResponse,response.pingResponse),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,updateResponse,response.updateResponse),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,setBoardLightColorResponse,response.setBoardLightColorResponse),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,getBoardDetailsResponse,response.getBoardDetailsResponse),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,loadBoardConfigurationResponse,response.loadBoardConfigurationResponse),   9)
#define MyProjectResponse_CALLBACK NULL
#define MyProjectResponse_DEFAULT NULL
#define MyProjectResponse_response_invalidCommandResponse_MSGTYPE InvalidCommandResponse
#define MyProjectResponse_response_helloQromaResponse_MSGTYPE HelloQromaResponse
#define MyProjectResponse_response_mathResponse_MSGTYPE MathResponse
#define MyProjectResponse_response_setUpdateConfigurationResponse_MSGTYPE SetUpdateConfigurationResponse
#define MyProjectResponse_response_pingResponse_MSGTYPE PingResponse
#define MyProjectResponse_response_updateResponse_MSGTYPE UpdateResponse
#define MyProjectResponse_response_setBoardLightColorResponse_MSGTYPE SetBoardLightColorResponse
#define MyProjectResponse_response_getBoardDetailsResponse_MSGTYPE GetBoardDetailsResponse
#define MyProjectResponse_response_loadBoardConfigurationResponse_MSGTYPE LoadBoardConfigurationResponse

extern const pb_msgdesc_t HelloQromaRequest_msg;
extern const pb_msgdesc_t HelloQromaResponse_msg;
extern const pb_msgdesc_t MathRequest_msg;
extern const pb_msgdesc_t MathResult_Add_msg;
extern const pb_msgdesc_t MathResult_Subtract_msg;
extern const pb_msgdesc_t MathResult_AddAndSubtract_msg;
extern const pb_msgdesc_t MathResponse_msg;
extern const pb_msgdesc_t FwUpdateConfiguration_msg;
extern const pb_msgdesc_t SetUpdateConfiguration_msg;
extern const pb_msgdesc_t SetUpdateConfigurationResponse_msg;
extern const pb_msgdesc_t UptimeUpdateResponse_msg;
extern const pb_msgdesc_t ProgressIndicatorUpdateResponse_msg;
extern const pb_msgdesc_t UpdateResponse_msg;
extern const pb_msgdesc_t PingRequest_msg;
extern const pb_msgdesc_t PingResponse_msg;
extern const pb_msgdesc_t MyProjectDetails_msg;
extern const pb_msgdesc_t FirmwareDetails_msg;
extern const pb_msgdesc_t GetBoardDetailsRequest_msg;
extern const pb_msgdesc_t GetBoardDetailsResponse_msg;
extern const pb_msgdesc_t SetBoardLightColorRequest_msg;
extern const pb_msgdesc_t SetBoardLightColorResponse_msg;
extern const pb_msgdesc_t LoadBoardConfigurationResponse_msg;
extern const pb_msgdesc_t InvalidCommandResponse_msg;
extern const pb_msgdesc_t MyProjectCommand_msg;
extern const pb_msgdesc_t MyProjectResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HelloQromaRequest_fields &HelloQromaRequest_msg
#define HelloQromaResponse_fields &HelloQromaResponse_msg
#define MathRequest_fields &MathRequest_msg
#define MathResult_Add_fields &MathResult_Add_msg
#define MathResult_Subtract_fields &MathResult_Subtract_msg
#define MathResult_AddAndSubtract_fields &MathResult_AddAndSubtract_msg
#define MathResponse_fields &MathResponse_msg
#define FwUpdateConfiguration_fields &FwUpdateConfiguration_msg
#define SetUpdateConfiguration_fields &SetUpdateConfiguration_msg
#define SetUpdateConfigurationResponse_fields &SetUpdateConfigurationResponse_msg
#define UptimeUpdateResponse_fields &UptimeUpdateResponse_msg
#define ProgressIndicatorUpdateResponse_fields &ProgressIndicatorUpdateResponse_msg
#define UpdateResponse_fields &UpdateResponse_msg
#define PingRequest_fields &PingRequest_msg
#define PingResponse_fields &PingResponse_msg
#define MyProjectDetails_fields &MyProjectDetails_msg
#define FirmwareDetails_fields &FirmwareDetails_msg
#define GetBoardDetailsRequest_fields &GetBoardDetailsRequest_msg
#define GetBoardDetailsResponse_fields &GetBoardDetailsResponse_msg
#define SetBoardLightColorRequest_fields &SetBoardLightColorRequest_msg
#define SetBoardLightColorResponse_fields &SetBoardLightColorResponse_msg
#define LoadBoardConfigurationResponse_fields &LoadBoardConfigurationResponse_msg
#define InvalidCommandResponse_fields &InvalidCommandResponse_msg
#define MyProjectCommand_fields &MyProjectCommand_msg
#define MyProjectResponse_fields &MyProjectResponse_msg

/* Maximum encoded size of messages (where known) */
#define FirmwareDetails_size                     93
#define FwUpdateConfiguration_size               8
#define GetBoardDetailsRequest_size              2
#define GetBoardDetailsResponse_size             148
#define HelloQromaRequest_size                   21
#define HelloQromaResponse_size                  63
#define InvalidCommandResponse_size              51
#define LoadBoardConfigurationResponse_size      12
#define MY_PROJECT_MESSAGES_PB_H_MAX_SIZE        MyProjectResponse_size
#define MathRequest_size                         14
#define MathResponse_size                        14
#define MathResult_AddAndSubtract_size           12
#define MathResult_Add_size                      6
#define MathResult_Subtract_size                 6
#define MyProjectCommand_size                    23
#define MyProjectDetails_size                    51
#define MyProjectResponse_size                   151
#define PingRequest_size                         6
#define PingResponse_size                        12
#define ProgressIndicatorUpdateResponse_size     51
#define SetBoardLightColorRequest_size           18
#define SetBoardLightColorResponse_size          53
#define SetUpdateConfigurationResponse_size      12
#define SetUpdateConfiguration_size              12
#define UpdateResponse_size                      53
#define UptimeUpdateResponse_size                6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
