/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "qroma-lights-commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SaveQromaStrip_CurrentState, SaveQromaStrip_CurrentState, AUTO)


PB_BIND(QromaStripCommand, QromaStripCommand, AUTO)


PB_BIND(SetQromaDeviceName, SetQromaDeviceName, AUTO)


PB_BIND(UseCurrentSetupOnStartup, UseCurrentSetupOnStartup, AUTO)


PB_BIND(QromaLightsDeviceCommand, QromaLightsDeviceCommand, AUTO)


PB_BIND(QromaLightsDeviceError, QromaLightsDeviceError, AUTO)


PB_BIND(QromaLightsResponse, QromaLightsResponse, 2)




