/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "qroma-lights-types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QromaStripColor, QromaStripColor, AUTO)


PB_BIND(QromaStrip_WS2812FX_Animation, QromaStrip_WS2812FX_Animation, AUTO)


PB_BIND(QromaStrip_WS2812FX_IoSettings, QromaStrip_WS2812FX_IoSettings, AUTO)


PB_BIND(QromaStripConfig, QromaStripConfig, AUTO)


PB_BIND(QromaLightsDeviceConfig, QromaLightsDeviceConfig, 2)









